export const ACTION_TYPE = {
  SET_USER: "SET_USER",
  SET_PRODUCT_DATA: "SET_PRODUCT_DATA",
  LOGOUT: "LOGOUT",
  SET_PRODUCT: "SET_PRODUCT",
  SET_PRODUCTS: "SET_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  DELETE_PRODUCTS_FROM_CART: "DELETE_PRODUCTS_FROM_CART",
  DELETE_PRODUCT_FROM_CART: "DELETE_PRODUCT_FROM_CART",
};
